### ISSUE TITLE
Json document too large

### ISSUE THREAD

**Issue by dimitar-dimitrow** [eclipse-kanto/aws-connector#3]
Update performs a merge in the shadow document. When a container is deleted, the container management SoftwareUpdatable feature send Ditto installedDependencies property modify with the deleted container missing. As in the AWS shadows a merge is performed the deleted container persist in the installedDependency part of the shadow document. Eventually this leads to over the limit shadow document:
 ```
{
    "timestamp": "2023-09-25 13:15:20.495",
    "logLevel": "ERROR",
    "traceId": "8549dcc6-87b6-a5db-75ab-f442872a02fa",
    "accountId": "797412740850",
    "status": "Failure",
    "eventType": "UpdateThingShadow",
    "protocol": "MQTT",
    "deviceShadowName": "edge:SF3-C-0006W",
    "topicName": "$aws/things/edge:SF3-C-0006W/shadow/name/edge:containers:SoftwareUpdatable/update",
    "details": "Json document too large.  Size is 8359, max allowed: 8192"
}
```

**Comment by IvanBoychevMarinov** [comment]
I had few ideas about this issue. 
The cleanest one in aws interaction terms would be to send a get request, wait for the response and merge the result, but this would require providing access to the aws publisher and subscriber, manually wait for the response, and slower processing of the messages.
One hacky solution I had in mind was to prepare two messages - first delete the corresponding feature and then publish the update, but there is no message order guaranteed, so we might end with missing shadow.

The solution I choose seems the least awkward in the current architecture, although it is a bit hacky on its own.

I decided to register a cloud message handler. this message handler
* Subscribes to update/accepted, delete/accepted topics.
* Keeps track of the last known state of the shadows.
* Produces no output messages (smelly, smelly :D).

The Passthrough Device Handler (We should discuss naming here) knows about this message handler, but under another interface, like Shadow State Holder. When producing messages, the Passthrough Device Handler asks the   Shadow State Holder about the current state of given shadow and merges the current and new state recursively by adding some nils if something is present in the current state but missing in the new state.

What do you think @dimitar-dimitrow @k-gostev
